In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
s = np.random.rand(100,100)

In [21]:
df = pd.DataFrame(s)

In [22]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.290827,0.373862,0.133820,0.206235,0.876222,0.526290,0.041632,0.180394,0.833626,0.516880,...,0.205058,0.207665,0.550498,0.625171,0.516308,0.961070,0.390047,0.691044,0.704983,0.930269
1,0.920815,0.320749,0.008305,0.066589,0.244215,0.119009,0.709906,0.791673,0.541077,0.373553,...,0.741222,0.908509,0.871142,0.895327,0.579803,0.574378,0.884403,0.826571,0.415192,0.581149
2,0.541376,0.680507,0.185640,0.625978,0.057758,0.853141,0.977742,0.772709,0.630056,0.827009,...,0.947938,0.033822,0.765726,0.434794,0.883126,0.914267,0.867473,0.763487,0.705323,0.916327
3,0.243234,0.489053,0.744088,0.480522,0.601976,0.344025,0.572290,0.178366,0.167690,0.479896,...,0.277109,0.223534,0.226631,0.327226,0.211289,0.502960,0.055275,0.431995,0.816532,0.340199
4,0.322505,0.121677,0.237501,0.918169,0.334366,0.777134,0.738319,0.098259,0.847986,0.538584,...,0.331205,0.164800,0.226144,0.431029,0.006465,0.949774,0.975491,0.120249,0.656153,0.089948

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 100 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
 3   3       100 non-null    float64
 4   4       100 non-null    float64
 5   5       100 non-null    float64
 6   6       100 non-null    float64
 7   7       100 non-null    float64
 8   8       100 non-null    float64
 9   9       100 non-null    float64
 10  10      100 non-null    float64
 11  11      100 non-null    float64
 12  12      100 non-null    float64
 13  13      100 non-null    float64
 14  14      100 non-null    float64
 15  15      100 non-null    float64
 16  16      100 non-null    float64
 17  17      100 non-null    float64
 18  18      100 non-null    float64
 19  19      100 non-null    float64
 20  20      100 non-null    float64
 21  21      100 non-null    float64
 22  22      100 non-null    float64
 23  23      100 non-null    float64
 24  24      100 non-null    float64
 25  25      100 non-null    float64
 26  26      100 non-null    float64
 27  27      100 non-null    float64
 28  28      100 non-null    float64
 29  29      100 non-null    float64
 30  30      100 non-null    float64
 31  31      100 non-null    float64
 32  32      100 non-null    float64
 33  33      100 non-null    float64
 34  34      100 non-null    float64
 35  35      100 non-null    float64
 36  36      100 non-null    float64
 37  37      100 non-null    float64
 38  38      100 non-null    float64
 39  39      100 non-null    float64
 40  40      100 non-null    float64
 41  41      100 non-null    float64
 42  42      100 non-null    float64
 43  43      100 non-null    float64
 44  44      100 non-null    float64
 45  45      100 non-null    float64
 46  46      100 non-null    float64
 47  47      100 non-null    float64
 48  48      100 non-null    float64
 49  49      100 non-null    float64
 50  50      100 non-null    float64
 51  51      100 non-null    float64
 52  52      100 non-null    float64
 53  53      100 non-null    float64
 54  54      100 non-null    float64
 55  55      100 non-null    float64
 56  56      100 non-null    float64
 57  57      100 non-null    float64
 58  58      100 non-null    float64
 59  59      100 non-null    float64
 60  60      100 non-null    float64
 61  61      100 non-null    float64
 62  62      100 non-null    float64
 63  63      100 non-null    float64
 64  64      100 non-null    float64
 65  65      100 non-null    float64
 66  66      100 non-null    float64
 67  67      100 non-null    float64
 68  68      100 non-null    float64
 69  69      100 non-null    float64
 70  70      100 non-null    float64
 71  71      100 non-null    float64
 72  72      100 non-null    float64
 73  73      100 non-null    float64
 74  74      100 non-null    float64
 75  75      100 non-null    float64
 76  76      100 non-null    float64
 77  77      100 non-null    float64
 78  78      100 non-null    float64
 79  79      100 non-null    float64
 80  80      100 non-null    float64
 81  81      100 non-null    float64
 82  82      100 non-null    float64
 83  83      100 non-null    float64
 84  84      100 non-null    float64
 85  85      100 non-null    float64
 86  86      100 non-null    float64
 87  87      100 non-null    float64
 88  88      100 non-null    float64
 89  89      100 non-null    float64
 90  90      100 non-null    float64
 91  91      100 non-null    float64
 92  92      100 non-null    float64
 93  93      100 non-null    float64
 94  94      100 non-null    float64
 95  95      100 non-null    float64
 96  96      100 non-null    float64
 97  97      100 non-null    float64
 98  98      100 non-null    float64
 99  99      100 non-null    float64
dtypes: float64(100)
memory usage: 78.2 KB

In [24]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.494925,0.469828,0.471862,0.482258,0.559659,0.464490,0.498860,0.476649,0.559707,0.484123,...,0.520306,0.479618,0.537885,0.524617,0.467199,0.546189,0.490864,0.547249,0.553014,0.490587
std,0.302483,0.264477,0.284931,0.284695,0.294433,0.286410,0.285167,0.272254,0.282635,0.266733,...,0.312744,0.276395,0.290225,0.315854,0.283818,0.288477,0.303268,0.291481,0.280458,0.259427
min,0.007336,0.017596,0.005548,0.002903,0.000708,0.026200,0.016501,0.001595,0.012601,0.003942,...,0.009095,0.009881,0.008319,0.000398,0.006465,0.013608,0.004789,0.027376,0.003564,0.000246
25%,0.235903,0.287844,0.203493,0.222626,0.312572,0.228647,0.249992,0.254850,0.326070,0.274804,...,0.240575,0.226131,0.322171,0.243369,0.230785,0.282572,0.232767,0.299234,0.334211,0.306996
50%,0.502310,0.438520,0.515567,0.484884,0.606915,0.459589,0.484682,0.480464,0.568323,0.489444,...,0.543343,0.477636,0.549833,0.514356,0.470931,0.580672,0.473324,0.570764,0.597429,0.481418
75%,0.769775,0.696868,0.691978,0.719352,0.809527,0.696363,0.739577,0.723937,0.814787,0.677948,...,0.823763,0.709634,0.814409,0.823315,0.691630,0.791993,0.762762,0.794121,0.789990,0.706242
max,0.988225,0.996215,0.992718,0.965721,0.977814,0.989488,0.989727,0.993802,0.999258,0.980118,...,0.985952,0.999690,0.989516,0.996966,0.997372,0.986655,0.978791,0.995921,0.996427,0.995064

In [26]:
np.median(df)

0.5123238738068683

In [27]:
np.median(df,axis=1)

array([0.43577607, 0.5376704 , 0.5375986 , 0.49600629, 0.51168636,
       0.52164305, 0.45677936, 0.51219501, 0.56892985, 0.47437698,
       0.4975231 , 0.44543491, 0.50854166, 0.51818361, 0.44936   ,
       0.59815779, 0.52937994, 0.53222881, 0.49317632, 0.4120194 ,
       0.53954372, 0.51557416, 0.54305013, 0.59528355, 0.50041125,
       0.56544345, 0.56816832, 0.48933037, 0.55680773, 0.57828607,
       0.55303353, 0.49801882, 0.43129117, 0.50635161, 0.51636662,
       0.52943659, 0.46556552, 0.47402228, 0.48205089, 0.47579082,
       0.47840048, 0.56358383, 0.58578422, 0.60624504, 0.4530069 ,
       0.52331584, 0.45902009, 0.551753  , 0.54340163, 0.50759374,
       0.48017635, 0.46665221, 0.44125427, 0.48741206, 0.45019175,
       0.51952531, 0.56833516, 0.52594694, 0.5490588 , 0.45119595,
       0.51314157, 0.48083604, 0.59793825, 0.5347638 , 0.55247504,
       0.51401573, 0.57673412, 0.4862516 , 0.46761698, 0.44307119,
       0.51697278, 0.5261229 , 0.49922444, 0.44019974, 0.52420574,
       0.48334113, 0.5034205 , 0.59289042, 0.55693962, 0.60169403,
       0.49131728, 0.49907666, 0.4654083 , 0.48384659, 0.54400026,
       0.46361847, 0.46534447, 0.44389731, 0.49581785, 0.47107226,
       0.50415879, 0.49864879, 0.55099695, 0.53035174, 0.57886746,
       0.47734744, 0.51642184, 0.40492054, 0.44710986, 0.53013549])

In [29]:
np.median(df,axis=0)

array([0.50231002, 0.43852004, 0.5155666 , 0.48488429, 0.6069149 ,
       0.45958906, 0.48468249, 0.48046448, 0.56832271, 0.4894439 ,
       0.49729371, 0.51812964, 0.5079712 , 0.50655925, 0.57796619,
       0.56096251, 0.4969597 , 0.50174112, 0.50829905, 0.50640836,
       0.50584267, 0.44528252, 0.4608055 , 0.57470727, 0.51325693,
       0.55598402, 0.50582764, 0.50984508, 0.52702358, 0.57816692,
       0.59956817, 0.523434  , 0.48988823, 0.46864324, 0.49861202,
       0.54143842, 0.56197091, 0.53166647, 0.67418191, 0.43861461,
       0.49277575, 0.56651289, 0.55534761, 0.46950757, 0.48900506,
       0.46178273, 0.45914712, 0.53919679, 0.53416647, 0.48163565,
       0.59957169, 0.52385056, 0.49981856, 0.45448702, 0.47706058,
       0.51574059, 0.54414927, 0.47994162, 0.55413074, 0.4981632 ,
       0.53079689, 0.45250238, 0.52037031, 0.55820352, 0.40553108,
       0.51383625, 0.48387335, 0.57781249, 0.46565498, 0.5264704 ,
       0.48418018, 0.53902304, 0.51681178, 0.47661928, 0.49643514,
       0.51657057, 0.44940363, 0.56842773, 0.44668745, 0.51768329,
       0.51567273, 0.64489146, 0.47889219, 0.56701997, 0.51131608,
       0.4943652 , 0.519456  , 0.44949123, 0.59962338, 0.41901302,
       0.54334304, 0.4776361 , 0.54983265, 0.51435579, 0.47093083,
       0.58067209, 0.47332429, 0.57076439, 0.59742903, 0.48141759])